/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.UnityRoboticsDemo
{
    public class SaveBinaryFileResponse : Message
    {
        public const string RosMessageName = "unity_robotics_demo_msgs/SaveBinaryFile";

        public string name { get; set; }

        public SaveBinaryFileResponse()
        {
            this.name = "";
        }

        public SaveBinaryFileResponse(string name)
        {
            this.name = name;
        }
    }
}
