//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class ShuffleResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Shuffle";
        public override string RosMessageName => k_RosMessageName;

        public PosRotMsg output;

        public ShuffleResponse()
        {
            this.output = new PosRotMsg();
        }

        public ShuffleResponse(PosRotMsg output)
        {
            this.output = output;
        }

        public static ShuffleResponse Deserialize(MessageDeserializer deserializer) => new ShuffleResponse(deserializer);

        private ShuffleResponse(MessageDeserializer deserializer)
        {
            this.output = PosRotMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "ShuffleResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
